---
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vale:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: errata-ai/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff
        with:
          fail_on_error: true
          reporter: github-check
          vale_flags: "--glob=*.{md,txt}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0
          persist-credentials: false
      - uses: super-linter/super-linter/slim@2da136927bd4a73596db63044b504547c62cb854
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IGNORE_GENERATED_FILES: true
          MARKDOWN_CONFIG_FILE: .markdown-lint.yaml
          SUPPRESS_POSSUM: true
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
          VALIDATE_SPELL_CODESPELL: false
