---
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vale:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: errata-ai/vale-action@85f9f7f2c5f449ac0ae5b66662961bae3f77ca6a
        with:
          fail_on_error: true
          reporter: github-check
          vale_flags: "--glob=*.{md,txt}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0
          persist-credentials: false
      - uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IGNORE_GENERATED_FILES: true
          MARKDOWN_CONFIG_FILE: .markdown-lint.yaml
          SUPPRESS_POSSUM: true
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
          VALIDATE_SPELL_CODESPELL: false
